# Verino is maintained by one developer.
# Your sponsorship keeps it alive, maintained, and MIT licensed forever.
# Thank you for considering supporting open source work.

github: [walebuilds]
open_collective: boastack
patreon: walebuilds